#!/bin/bash
sudo apt-get update 
sudo apt-get -y install build-essential libgcc1:i386 lib32z1 lib32ncurses5 lib32bz2-1.0 screen lib32stdc++6 libstdc++6:i386 libssl1.0.0:i386 libstdc++6:i386 libssl1.0.0:i386 libcurl3-gnutls libcurl3-gnutls:i386

