#!/bin/bash
#$HOME/.bin/updatecs

if [ -z "$CSPORT" ]; then
    CSPORT=27015
fi

if [ -z "$1" ]; then
    MAP=de_dust2
fi

echo running at port CSPORT=$CSPORT with map $MAP
cd $HOME/cs
./hlds_linux -game -console cstrike +maxplayers 10 +map $MAP +port $CSPORT #  +sv_lan 1 -noipx -nomaster -noupdate -insecure
