#!/bin/bash
$HOME/.bin/updatecss

if [ -z "$CSSPORT" ]; then
    CSSPORT=27015
fi

if [ -z "$1" ]; then
    MAP=de_dust2
fi

echo running at port CSSPORT=$CSSPORT with map $MAP

css/srcds_run -game cstrike +maxplayers 10 +map $MAP +port $CSSPORT
