#!/bin/bash
$HOME/.bin/updateinsurgency
if [ -z "$1" ]; then
    MAP=buhriz
else
    MAP=$1	
fi

if [ -z "$INSPORT" ]; then
    INSPORT=27015 
fi  

echo running at port INSPORT=$INSPORT with map $MAP

$HOME/insurgency/srcds_run -game insurgency -port $INSPORT -console +ins_bot_quota 13 +maxplayers 24 +map $MAP
