#!/bin/sh
echo running at port RUSTPORT=$RUSTPORT 

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/RustDedicated_Data/Plugins/x86_64

cd $HOME/rust
./runds.sh +server.port $RUST_PORT +server.hostname "Ballistic Guitar Case" # +server.maxplayers 1
