#!/bin/sh
$HOME/.bin/updatetf2

if [ -z "$1" ]
then
    MAP="+randommap"
else
    echo $1 > $HOME/tf2/tf/cfg/mapcycle.tmp
    MAP="+map $1 +mapcyclefile mapcycle.tmp"
fi

if [ -z "$TF2PORT" ]
then
    TF2PORT=27015
else
    TF2PORT=$2
fi
echo running at port TF2PORT=$TF2PORT with map $MAP
$HOME/tf2/srcds_run -game tf -console -port $TF2PORT +sv_pure 1 $MAP +maxplayers 18
