#!/bin/sh
if [ -z "$1" ]
then
    PORT=27015
    MAP=ctf_2fort
elif [ -z "$2" ]
then
    MAP=$1
else
    MAP=$1	
    PORT=$2
fi

$HOME/tf2/srcds_run -game tf -console -port $PORT +sv_pure 1 +map $MAP +maxplayers 18
