#!/bin/sh
while getopts ":v" opt; do
  case $opt in
    v)
          VERIFY_FLAG=validate
      ;;
  esac
done
steamcmd \
+@ShutdownOnFailedCommand 1 \
+@NoPromptForPassword 1 \
+login anonymous \
+force_install_dir $HOME/insurgency/ \
+app_update 237410 $VERIFY_FLAG \
+quit
