#!/bin/bash
#use *apt install steamcmd* instead
echo THIS IS OLD



echo "rm -rfv $HOME/steamcmd_linux*"
echo "wget http://media.steampowered.com/client/steamcmd_linux.tar.gz"
echo "tar -vzxf steamcmd_linux.tar.gz -C $HOME/"
echo "rm steamcmd_linux.tar.gz "
