#!/bin/sh
while getopts ":v" opt; do
  case $opt in
    v)
          VERIFY_FLAG=validate
      ;;
  esac
done
$HOME/steamcmd.sh \
+@ShutdownOnFailedCommand 1 \
+@NoPromptForPassword 1 \
+login anonymous \
+force_install_dir $HOME/tf2/ \
+app_update 232250 $VERIFY_FLAG \
+quit
