#!/bin/sh
while getopts ":v" opt; do
  case $opt in
    v)
          VERIFY_FLAG=validate
      ;;
  esac
done

steamcmd \
+@ShutdownOnFailedCommand 1 \
+@NoPromptForPassword 1 \
+login anonymous \
+force_install_dir $HOME/rust/ \
+app_update 258550 $VERIFY_FLAG \
+quit
