#!/bin/sh
while getopts ":v" opt; do
  case $opt in
    v)
          VERIFY_FLAG=validate
      ;;
  esac
done
/home/sourceds/steamcmd.sh \
+@ShutdownOnFailedCommand 1 \
+@NoPromptForPassword 1 \
+login anonymous \
+force_install_dir /home/sourceds/gmod/ \
+app_update 4020 $VERIFY_FLAG \
+quit

